### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by unlight** [piuccio/sublime-esformatter#63]
v1.6.5, node v5.3.0, win8-64,

My javascript is valid.
When trying to format sublime throws:

![](https://i.gyazo.com/b00e0ba74206d6edd9e3ec46d26de01d.png)

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at D:\Progs\Sublime-Text-3\Data\Packages\EsFormatter\lib\esformatter.js:22131:20
    at Object.<anonymous> (D:\Progs\Sublime-Text-3\Data\Packages\EsFormatter\lib\esformatter.js:22160:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by piuccio** [comment]
how big is the file?

**Comment by unlight** [comment]
It happens with any file.
~ 17 Lines, 805 chars

**Comment by leobalter** [comment]
It seems this error is happening while parsing the config settings in JSON.

you might need to double check it.

**Comment by unlight** [comment]
I will check.
But it was clean install, I didn't do anything with settings.
